# Generated by Django 2.2.4 on 2020-03-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20200323_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
