# Generated by Django 2.2.4 on 2020-03-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_auto_20200324_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailAddress',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
