# Generated by Django 2.2.4 on 2020-03-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_auto_20200324_1641'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
