version: "3"
services:

  db:
    image: mysql
  models:
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    networks:
      - backend
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py loaddata db_p2.json && mod_wsgi-express start-server --working-directory . --reload-on-changes clothesmicroservices/wsgi.py"

networks:
  backend: